#%RAML 1.0
title: anypoint
/listAllUnitedFlights:
  get:
    responses:
      200:
        body:
            application/json:
              example: !include examples/united.json
/unitedFlightsByDestination:
 get: 
  queryParameters: 
   destination:
    required: true
  responses: 
   200:
    body: 
     application/json:
        example: !include examples/united.json
     
